# Display
name: SurvivalMysteryChests
author: PYRRH4
website: www.pyrrh4.be
description: 'Mystery chests for your survival server !'
# Techy
version: 1.7.5
main: be.pyrrh4.survivalmysterychests.SMC
depend: [PyrCore]
commands:
  survivalmysterychests:
    description: Main command !
    aliases: [smc]
permissions:
  smc.chest.create:
    default: op
  smc.key.give:
    default: op
