name: SurvivalMysteryChests
version: 1.7.2
main: be.pyrrh4.survivalmysterychests.SMC
depend: [PyrCore]
author: PYRRH4
website: www.pyrrh4.be
commands:
  survivalmysterychests:
    description: Main command !
    aliases: [smc]
permissions:
  smc.chest.create:
    default: op
  smc.key.give:
    default: op
