#----------------------------------------------------------------------------------------------------
# Configuration file for SurvivalMysteryChests plugin !
#----------------------------------------------------------------------------------------------------

# Locale

locale: survivalmysterychests_en_US.yml

#----------------------------------------------------------------------------------------------------
# Items
#----------------------------------------------------------------------------------------------------

items: 
  not-selected: 
    type: STAINED_GLASS_PANE
    data: 0
    amount: 1
    name: '&f&l???????????????'
    lore:
      - '&7&l???????????????'
  selected: 
    type: CHEST
    data: 0
    amount: 1
    name: '&a&l???????????????'
    lore:
      - '&7&lSelected !'

#----------------------------------------------------------------------------------------------------
# Sounds
#----------------------------------------------------------------------------------------------------
# List of sounds : http://www.pyrrh4.be/doc/sounds/
#----------------------------------------------------------------------------------------------------

sounds: 
  select: FIREWORK_BLAST2
  roll: ITEM_PICKUP
  finished: FIREWORK_LAUNCH
  reward: ORB_PICKUP

#----------------------------------------------------------------------------------------------------
# Here you can create unlimited keys types.
# You can find a tutorial on the official plugin page --> https://goo.gl/qv1frK
#----------------------------------------------------------------------------------------------------

keys: 

# Cheat key

  cheat: 
    type: NETHER_STAR
    data: 0
    name: &aCheat key
    lore:
      - &7With this key, you can
      - &7open a &bCheat chest &7!

#----------------------------------------------------------------------------------------------------
# Here you can create unlimited chests types.
# You can find a tutorial on the official plugin page --> https://goo.gl/qv1frK
#----------------------------------------------------------------------------------------------------

chests: 

# Example : Free chest

  free: 
    settings: 
      name: &bFree chest
      price: &aFree
      delay: 120
      size: 54
      choice: 5
    wins: 
      dirt: 
        chance: 40
        item: DIRT 0 random{1,32}
      stone: 
        chance: 40
        item: STONE 0 random{1,32}
      cobblestone: 
        chance: 40
        item: COBBLESTONE 0 random{1,32}
      wood: 
        chance: 40
        item: WOOD 0 random{1,32}
      log: 
        chance: 40
        item: LOG 0 random{1,32}

# Example : PvP chest

  pvp: 
    settings: 
      name: &bPvP chest
      price: money 500
      delay: 0
      size: 27
      choice: 2
    wins: 
      iron-sword: 
        chance: 40
        item: IRON_SWORD 0 1
        enchantments:
          - DAMAGE_ALL 1
          - DURABILITY 1
      diamond-sword: 
        chance: 30
        item: DIAMOND_SWORD 0 1
        enchantments:
          - KNOCKBACK 1
      bow: 
        chance: 30
        item: BOW 0 1
      arrow: 
        chance: 40
        item: ARROW 0 random{5,20)
      golden-apple: 
        chance: 10
        item: GOLDEN_APPLE 0 random{1,2)
        name: &bA GOLDEN APPLE
      cooked-beef: 
        chance: 50
        item: COOKED_BEEF 0 random{1,16)
        lore:
          - &7This is an awesome cooked beef !
      iron-chestplate: 
        chance: 20
        item: IRON_CHESTPLATE 0 1
      diamond-leggings: 
        chance: 20
        item: DIAMOND_LEGGINGS 0 1
        name: &bDiamond leggings...
        lore:
          - &7with name and lore !

# Example : Cheat chest

  cheat: 
    settings: 
      name: &bCheat chest
      price: key cheat
      delay: 0
      size: 27
      choice: 1
    wins: 
      golden-apple: 
        chance: 50
        commands:
          - 'broadcast &aPYRRH4 &7won a golden apple ! :O'
        item: GOLDEN_APPLE 1 1
      ghast-tear: 
        chance: 50
        item: GHAST_TEAR 0 random{1,10}
      golden-carrot: 
        chance: 50
        item: GOLDEN_CARROT 0 random{1,10}
      ender-pearl: 
        chance: 50
        item: ENDER_PEARL 0 random{1,16}
      blaze-rod: 
        chance: 50
        item: BLAZE_ROD 0 random{1,15}
      speckled-melon: 
        chance: 50
        item: SPECKLED_MELON 0 random{1,10}
      diamond: 
        chance: 50
        item: DIAMOND 0 random{1,15}
      glowstone: 
        chance: 50
        item: GLOWSTONE 0 random{1,20}
      nether-stalk: 
        chance: 50
        item: NETHER_STALK 0 random{1,20}
      creeper-egg: 
        chance: 50
        item: MONSTER_EGG 50 random{1,10}
      tnt: 
        chance: 50
        item: TNT 0 random{1,20}
